import '../styles/globals.css'
// import { Inter } from 'next/font/google'
import { font } from './font.js'
import Navigation from '../components/Navigation'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first App with Next 13',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang='es'>
      {/* <body className={inter.className}> */}
      {/* <body className={font.className}> */}
      <body className={font.variable}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
