import '../styles/globals.css'
import { Inter } from 'next/font/google'
import Navigation from '../components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first App with Next 13',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang='es'>
      {/* <head>My first App with Next 13</head> */}
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
